import turtle

turtle.write("F"*7)
turtle.penup()
turtle.goto(0,-10)
turtle.pendown()
turtle.write("F"*2)
turtle.penup()
turtle.goto(0,-20)
turtle.pendown()
turtle.write("F"*7)
turtle.penup()
turtle.goto(0,-30)
turtle.pendown()
turtle.write("F"*2)
turtle.penup()
turtle.goto(0,-40)
turtle.pendown()
turtle.write("F"*2)

turtle.penup()
turtle.goto(60,0)
turtle.pendown()
turtle.write("U")
turtle.penup()
turtle.goto(110,0)
turtle.pendown()
turtle.write("U")
turtle.penup()
turtle.goto(60,-10)
turtle.pendown()
turtle.write("U")
turtle.penup()
turtle.goto(110,-10)
turtle.pendown()
turtle.write("U")
turtle.penup()
turtle.goto(60,-20)
turtle.pendown()
turtle.write("U")
turtle.penup()
turtle.goto(110,-20)
turtle.pendown()
turtle.write("U")
turtle.penup()
turtle.goto(70,-30)
turtle.pendown()
turtle.write("U")
turtle.penup()
turtle.goto(100,-30)
turtle.pendown()
turtle.write("U")
turtle.penup()
turtle.goto(80,-40)
turtle.pendown()
turtle.write("U"*3)

turtle.penup()
turtle.goto(160,0)
turtle.pendown()
turtle.write("NN")

turtle.penup()
turtle.goto(160,-10)
turtle.pendown()
turtle.write("NNN")

turtle.penup()
turtle.goto(160,-20)
turtle.pendown()
turtle.write("NN")

turtle.penup()
turtle.goto(160,-30)
turtle.pendown()
turtle.write("NN")

turtle.penup()
turtle.goto(160,-40)
turtle.pendown()
turtle.write("NN")

turtle.penup()
turtle.goto(180,-20)
turtle.pendown()
turtle.write("N")

turtle.penup()
turtle.goto(190,-30)
turtle.pendown()
turtle.write("N")

turtle.penup()
turtle.goto(210,0)
turtle.pendown()
turtle.write("NN")

turtle.penup()
turtle.goto(210,-10)
turtle.pendown()
turtle.write("NN")

turtle.penup()
turtle.goto(210,-20)
turtle.pendown()
turtle.write("NN")

turtle.penup()
turtle.goto(210,-30)
turtle.pendown()
turtle.write("NN")

turtle.penup()
turtle.goto(205,-40)
turtle.pendown()
turtle.write("NNN")
turtle.done()

