import turtle
turtle.penup()
turtle.goto(-300,300)
turtle.pendown()
turtle.write("a")
turtle.penup()
turtle.goto(-200,300)
turtle.pendown()
turtle.write("a^2")
turtle.penup()
turtle.goto(-100,300)
turtle.pendown()
turtle.write("a^3")

turtle.penup()
turtle.goto(-300,290)
turtle.pendown()
turtle.write("1")
turtle.penup()
turtle.goto(-200,290)
turtle.pendown()
turtle.write("1")
turtle.penup()
turtle.goto(-100,290)
turtle.pendown()
turtle.write("1")

turtle.penup()
turtle.goto(-300,280)
turtle.pendown()
turtle.write("2")
turtle.penup()
turtle.goto(-200,280)
turtle.pendown()
turtle.write("4")
turtle.penup()
turtle.goto(-100,280)
turtle.pendown()
turtle.write("8")

turtle.penup()
turtle.goto(-300,270)
turtle.pendown()
turtle.write("3")
turtle.penup()
turtle.goto(-200,270)
turtle.pendown()
turtle.write("9")
turtle.penup()
turtle.goto(-100,270)
turtle.pendown()
turtle.write("27")

turtle.penup()
turtle.goto(-300,260)
turtle.pendown()
turtle.write("4")
turtle.penup()
turtle.goto(-200,260)
turtle.pendown()
turtle.write("16")
turtle.penup()
turtle.goto(-100,260)
turtle.pendown()
turtle.write("64")

turtle.done()